### PR TITLE
Add icon for flickr

### PR DESCRIPTION
**Pull request by PierreBresson**
Just added a camera icon to represent flickr link (ionicons doesn't have any flickr icons).

### CODE REVIEW

**Comment by nielsenramon** [comment]
@PierreBresson Please attach a screenshot so I can see if it looks ok!

**Comment by PierreBresson** [comment]
screen shot 2016-11-28 at 13 37 20
Here it is

**Comment by nielsenramon** [comment]
@PierreBresson I think `icon-android-camera` would be a better fit height-wise. Can you try that one please?

**Comment by PierreBresson** [comment]
screen shot 2016-11-28 at 15 46 33

**Comment by PierreBresson** [comment]
Looks better indeed

**Comment by nielsenramon** [comment]
@PierreBresson Indeed it does. Thanks for the contribution!

**Pull request merged**
