### PR TITLE
Excerpt functionality

### PR DESCRIPTION
**Pull request by cmakara**
With this addition it is possible the use the first part of the post dynamically instead of using a static description, which is more flexible.

### CODE REVIEW

**Comment by nielsenramon** [comment]
@cmakara I kinda don't the the fact that this is very random. It shows pictures as well and if you don't pay enough attention it will be very weird to read. Look at the example for Chalk:
screen shot 2018-01-05 at 11 18 49

What does everyone else think?

**Comment by cmakara** [comment]
I wanted to keep the description solution intact and as a higher priority, so if someone would not want to use customisable excerpts they do not have to.

The use case I wanted to solve with this that I wanted to write posts which describes at the front what it will be about. Because of this, using the description, I had to duplicate content into the description field in md files. But with the excerpt separator, the first customisable amount of the post would be serving as the description.

**Comment by nielsenramon** [comment]
@cmakara Actually a good point. Can you also add this to the articles_by_tag page please?

I'll probably add some documentation about this.

**Comment by cmakara** [comment]
@nielsenramon  I did add it to the articles_by_tag page.

**Pull request merged**
