### PR TITLE
Add social icons for Bitcoin, Email & PGP

### PR DESCRIPTION
**Pull request by Mawalu**
example

### CODE REVIEW

**Comment by nielsenramon** [comment]
@Mawalu I do not feel the need to add PGP to a generic template, people can customise it as they please. So please remove that one :).

I think I prefer the @ (icon-ios-at) or Paperplane (icon-ios-paperplane) symbol for email as the email enveloppe is standing out to much in terms of height. What do you think?

**Comment by Mawalu** [comment]
The `icons-ios-at` looks very good but there is the same size issue as with the envelop icon. Any ideas how this could be fixed? 
bildschirmfoto vom 2016-11-03 17-46-13


I understand your problem with the PGP icon. Before I remove it can you imagine that it would be more usefull as a generic lock / crypto identity icon instead only PGP?

**Comment by nielsenramon** [comment]
@Mawalu You can use `icon-at` that one does not have the size issue!

Not sure about the lock as I haven't seen it on any blog before.
I want Chalk to be a bit more generic :). The lock icon feels like a login link or something tho.

**Comment by Mawalu** [comment]
Ok that makes totally sense. Hope this commit fixes all problems :)

**Comment by nielsenramon** [comment]
@Mawalu One more thing: Please use the same comment style as other social links: `Add your ...` :D
Then it's good to merge!

**Comment by nielsenramon** [comment]
@Mawalu Huge thanks!

**Pull request merged**
