### PR TITLE
Update setup

### PR DESCRIPTION
**Pull request by 95uxin**
Is it better to allow root? I have to add "--allow-root" every time I setup Chalk on my VPS!

### CODE REVIEW

**Comment by migueldemoura** [comment]
Why would you install bower assets with root?

**Comment by 95uxin** [comment]
@migueldemoura 

I do not know  your running environment, I ran it  on Linux Debian 8.

First, I try to run  `bin/setup`  command without `sudo` or `root`, here comes the log, says
`npm ERR! Please try running this command again as root/Administrator.`

```
wuy@debian7:~/chalk-master$ bin/setup 
The Gemfile's dependencies are satisfied
Fetching gem metadata from https://rubygems.org/..............
......
......
Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.
  Password: 
Bundle updated!
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/bower',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack: 
npm ERR!    [ '/usr/lib/nodejs/fstream/lib/writer.js:171:23',
npm ERR!      '/usr/lib/nodejs/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "bower"
npm ERR! cwd /home/wuy/chalk-master
npm ERR! node -v v0.10.29
......
.....
npm ERR! not ok code 0
```


Second, After I ran it with `sudo` or `root`, Here comes the log, says 
`bower ESUDO         Cannot be run with sudo` and ` run a command with sudo using --allow-root option`

```
wuy@debian7:~/chalk-master$ sudo bin/setup 
The Gemfile's dependencies are satisfied
.....
.....
Using jemoji 0.8.0
Bundle updated!
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
bower@1.8.0 /usr/local/lib/node_modules/bower
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
```

After I add `--allow-root` option in the `bin/setup` Everything is OK! :-)


Here all my steps before I run Chalk successfully:
```
$ sudo apt-get install ruby-full build-essential npm git

$ sudo ln -s /usr/bin/nodejs /usr/bin/node

$  sudo gem install jekyll bundle

~/chalk-master$ sudo  bundle install
add --allow-root to bin/setup
~/chalk-master$ sudo bin/setup
```

Hope it helps improvement!

**Comment by nielsenramon** [comment]
@95uxin Mostly this means you have everything setup with sudo on your dev machine which is not a good practise. I won't add this to the script because of that. Feel free to add it in your script of course.

**Comment by migueldemoura** [comment]
@95uxin, check out [RVM](https://rvm.io/), using it fixes this issue (and is a much better practice).

**Comment by 95uxin** [comment]
@migueldemoura Thanks! I will try!

**Pull request closed without merging**
