### PR TITLE
Updated README to reflect info in #154

### PR DESCRIPTION
**Pull request by nbulischeck**
It was discovered that Project sites and User sites behave differently when published, so as a precautionary measure I have included a note in the README.

### CODE REVIEW

**Comment by nielsenramon** [comment]
@nbulischeck Can you solve the conflicts please? :D

**Comment by nielsenramon** [comment]
@nbulischeck I would delete this one, pull latest master from origin and re-add your copy.

**Comment by migueldemoura** [comment]
Try creating a new branch, pulling from this master, adding your changes and creating a PR.

**Comment by nielsenramon** [comment]
@nbulischeck I'll add it no worries!

**Pull request closed without merging**
